# Generated by Django 3.1.5 on 2021-04-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('img', models.ImageField(upload_to='pics')),
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('gender', models.CharField(max_length=20)),
                ('rtpcr', models.BooleanField()),
                ('admission', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
